In [36]:
import pandas as pd 
import os

df = pd.read_csv(r"../data/raw/synthetic_transactions_messy.csv")

x = df["direction"].astype("string").str.strip().eq("").fillna(False)

y = df.duplicated(keep = False)

df[y]

,txn_id,user_id,transaction_date,narration,transaction_amount,transaction_category,direction,merchant_name,currency_code
100,TXN0000101,CUST0002,12-12-2025,DMART PAYMENT,-2044.03,Groceries,Debit,DMart,INR
32441,TXN0000101,CUST0002,12-12-2025,DMART PAYMENT,-2044.03,Groceries,Debit,DMart,INR

In [37]:
df.head()

,txn_id,user_id,transaction_date,narration,transaction_amount,transaction_category,direction,merchant_name,currency_code
0,TXN0000001,CUST0001,15-04-2025,TRAINING INSTITUTE PAYMENT,"₹21,812.91 DR",Education,Debit,Training Institute,INR
1,TXN0000002,CUST0001,2025/04/19,COURSE PLATFORM PAYMENT,"(3,611.60)",Education,Debit,Course Platform,INR
2,TXN0000003,CUST0001,2025-04-23,DMART PAYMENT,-1785.61,Groceries,Debit,DMart,INR
3,TXN0000004,CUST0001,2025-04-30,INTERNET PROVIDER PAYMENT,"INR 1,318.53 DR",Bills & Utilities,Debit,Internet Provider,INR
4,TXN0000005,CUST0001,2025-05-02,SALARY CREDIT Employer Payroll,"57,747.01 CR",Income,Credit,Employer Payroll,INR

In [38]:
import pandas as pd

from src.data_validation import validate_data

# Load the raw dataset.
df = pd.read_csv("../data/raw/synthetic_transactions_messy.csv")

print("Original shape:", df.shape)
print("Original columns:", df.columns.tolist())

ModuleNotFoundError: No module named 'src'