In [36]:
import pandas as pd 
import os

df = pd.read_csv(r"../data/raw/synthetic_transactions_messy.csv")

x = df["direction"].astype("string").str.strip().eq("").fillna(False)

y = df.duplicated(keep = False)

df[y]

,txn_id,user_id,transaction_date,narration,transaction_amount,transaction_category,direction,merchant_name,currency_code
100,TXN0000101,CUST0002,12-12-2025,DMART PAYMENT,-2044.03,Groceries,Debit,DMart,INR
32441,TXN0000101,CUST0002,12-12-2025,DMART PAYMENT,-2044.03,Groceries,Debit,DMart,INR

In [37]:
df.head()

,txn_id,user_id,transaction_date,narration,transaction_amount,transaction_category,direction,merchant_name,currency_code
0,TXN0000001,CUST0001,15-04-2025,TRAINING INSTITUTE PAYMENT,"₹21,812.91 DR",Education,Debit,Training Institute,INR
1,TXN0000002,CUST0001,2025/04/19,COURSE PLATFORM PAYMENT,"(3,611.60)",Education,Debit,Course Platform,INR
2,TXN0000003,CUST0001,2025-04-23,DMART PAYMENT,-1785.61,Groceries,Debit,DMart,INR
3,TXN0000004,CUST0001,2025-04-30,INTERNET PROVIDER PAYMENT,"INR 1,318.53 DR",Bills & Utilities,Debit,Internet Provider,INR
4,TXN0000005,CUST0001,2025-05-02,SALARY CREDIT Employer Payroll,"57,747.01 CR",Income,Credit,Employer Payroll,INR

In [11]:
import pandas as pd


df = pd.read_csv("../data/processed/enriched_transactions.csv")

credit_transactions = df.loc[df["transaction_type"] == "credit"]

total_inflow = (credit_transactions.groupby("customer_id")["amount"].sum().rename("total_inflow"))
total_inflow

customer_id
CUST0001     659885.23
CUST0002    1099531.21
CUST0003     594970.58
CUST0004     529626.54
CUST0005    1103806.64
               ...
CUST0596     823710.42
CUST0597     746285.81
CUST0598     713371.46
CUST0599    1100504.95
CUST0600     345880.27
Name: total_inflow, Length: 600, dtype: float64

In [15]:
df = pd.read_csv(r"../data/processed/customer_features.csv")

df.head()

,customer_id,total_inflow,total_outflow,net_cash_flow,transaction_count,average_transaction_amount
0,CUST0001,659885.23,278504.28,381380.95,61,15383.434590
1,CUST0002,1099531.21,446362.23,653168.98,66,23422.627879
2,CUST0003,594970.58,183924.10,411046.48,52,14978.743846
3,CUST0004,529626.54,167402.44,362224.10,41,17000.706829
4,CUST0005,1103806.64,381336.67,722469.97,58,25605.919138